
package cn.it.ws.dd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PhoneManager1", targetNamespace = "http://dd.ws.it.cn", wsdlLocation = "http://127.0.0.1:8088/ws/phoneSer?WSDL")
public class PhoneManager1
    extends Service
{

    private final static URL PHONEMANAGER1_WSDL_LOCATION;
    private final static WebServiceException PHONEMANAGER1_EXCEPTION;
    private final static QName PHONEMANAGER1_QNAME = new QName("http://dd.ws.it.cn", "PhoneManager1");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8088/ws/phoneSer?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PHONEMANAGER1_WSDL_LOCATION = url;
        PHONEMANAGER1_EXCEPTION = e;
    }

    public PhoneManager1() {
        super(__getWsdlLocation(), PHONEMANAGER1_QNAME);
    }

    public PhoneManager1(WebServiceFeature... features) {
        super(__getWsdlLocation(), PHONEMANAGER1_QNAME, features);
    }

    public PhoneManager1(URL wsdlLocation) {
        super(wsdlLocation, PHONEMANAGER1_QNAME);
    }

    public PhoneManager1(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PHONEMANAGER1_QNAME, features);
    }

    public PhoneManager1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneManager1(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort() {
        return super.getPort(new QName("http://dd.ws.it.cn", "PhoneServicePort"), PhoneService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneService
     */
    @WebEndpoint(name = "PhoneServicePort")
    public PhoneService getPhoneServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dd.ws.it.cn", "PhoneServicePort"), PhoneService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PHONEMANAGER1_EXCEPTION!= null) {
            throw PHONEMANAGER1_EXCEPTION;
        }
        return PHONEMANAGER1_WSDL_LOCATION;
    }

}
