
package ws.mywebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PhoneService", targetNamespace = "http://myWebService.ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PhoneService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ws.mywebservice.Phone
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPhoneInfo", targetNamespace = "http://myWebService.ws/", className = "ws.mywebservice.GetPhoneInfo")
    @ResponseWrapper(localName = "getPhoneInfoResponse", targetNamespace = "http://myWebService.ws/", className = "ws.mywebservice.GetPhoneInfoResponse")
    @Action(input = "http://myWebService.ws/PhoneService/getPhoneInfoRequest", output = "http://myWebService.ws/PhoneService/getPhoneInfoResponse")
    public Phone getPhoneInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
